export const NEWARRIVALS_GET = "GET_NEWARRIVALS";
export const NEWARRIVALS_POST = "POST_NEWARRIVALS";
export const NEWARRIVALS_PATCH = "PATCH_NEWARRIVALS";
export const NEWARRIVALS_DELETE = "DELETE_NEWARRIVALS";
export const NEWARRIVALS_SUCCESS = "SUCCESS_NEWARRIVALS";
export const NEWARRIVALS_SEARCH = "SEARCH_NEWARRIVALS";
export const NEWARRIVALS_ASC = "ASC_NEWARRIVALS";
export const NEWARRIVALS_DESC = "DESC_NEWARRIVALS";
export const NEWARRIVALS_PAGING1 = "PAGING1_NEWARRIVALS";
export const NEWARRIVALS_PAGING2 = "PAGING2_NEWARRIVALS";
export const NEWARRIVALS_PAGING3 = "PAGING3_NEWARRIVALS";


export const USER_GET = "GET_USER" 
export const USER_POST = "POST_USER" 
export const USER_SUCCESS = "SUCCESS_USER" 


export const CART_GET = "GET_CART"
export const CART_POST = "POST_CART"
export const CART_PATCH = "PATCH_CART"
export const CART_DELETE = "DELETE_CART"
export const CART_SUCCESS = "SUCCESS_CART"

