export const NEWARRIVALS_GET = "GET_NEWARRIVALS";
export const NEWARRIVALS_POST = "POST_NEWARRIVALS";
export const NEWARRIVALS_PATCH = "PATCH_NEWARRIVALS";
export const NEWARRIVALS_DELETE = "DELETE_NEWARRIVALS";
export const NEWARRIVALS_SUCCESS = "SUCCESS_NEWARRIVALS";


export const USER_GET = "GET_USER" 
export const USER_POST = "POST_USER" 
export const USER_SUCCESS = "SUCCESS_USER" 